version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      # Pode adicionar comandos pós-build, como mover arquivos ou realizar outras ações
      - echo "Build completed successfully"
artifacts:
  files:
    - "dist/**/*" # Enviar apenas arquivos de build
  discard-paths: yes # Evita incluir caminhos de diretório desnecessários
  exclude:
    - "node_modules/**/*" # Exclui explicitamente o diretório node_modules
