version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23
    # commands:
    # - npm install -g pnpm
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - "**/*"
  exclude-paths:
    - "src/**/*"
    - "CK*"
    - "docker*"
    - "entrypoint.sh"
    - "Docker*"
    - "laravel/**/*"
    - "app/**/*"
