version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23
  build:
    commands:
      - npm install
      - npm run build
      - ls -la
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - "dist/**/*" # Incluir somente os arquivos da pasta dist
  discard-paths: yes # Evita incluir caminhos de diretório desnecessários
  base-directory: dist # Define o diretório base para os artefatos (isso pode ser útil para evitar confusão com arquivos de outras pastas)
