version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23
  build:
    commands:
      - npm install
      - npm run build
      - ls -la
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - "**/*"
  exclude-paths:
    - "src/**/*"
    - "CK*"
    - "docker*"
    - "laravel/**/*"
    - "app/**/*"
