name: "autoservice"
services:
  redis:
    image: redis:alpine
    restart: "no"
    ports:
      - 6379:6379
    command: redis-server --requirepass "UNe#76iNR0gLaJEl" --bind 0.0.0.0 --protected-mode no
  db:
    image: postgres:17.2-alpine
    restart: "no"
    # restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_PASSWORD=disal
      - POSTGRES_DB=autoservice
      - POSTGRES_USER=disal
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    ports:
      - 6500:5432

  adminer:
    restart: "no"
    image: adminer
    # restart: always
    ports:
      - 8080:8080
  laravel:
    restart: "no"
    build:
      dockerfile: Dockerfile.laravel
      context: .
      # target: dev
    image: laravel
    ports:
      - 8888:8000
    volumes:
      # - laravel:/var/www/autoservice
      - ./laravel:/var/www/autoservice
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
# volumes:
#   laravel:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/rafael/projects/autoservice/laravel/