-- AlterTable
ALTER TABLE "LastSearch" ALTER COLUMN "startDate" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "endDate" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0);
