name: Deploy to Server

on:
  push:
    branches:
      - master  # O deploy ocorre sempre que houver um push para a branch master

jobs:
  build:
    runs-on: ubuntu-latest  # Usando uma máquina virtual Ubuntu

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurar o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # Versão do Node.js que você está usando

      # Passo 3: Instalar as dependências usando pnpm
      - name: Install dependencies
        run: |
          npm install -g pnpm  # Instalar o pnpm
          pnpm install  # Instalar as dependências do projeto

      # Passo 4: Realizar o build do projeto
      - name: Build the project
        run: |
          pnpm run build  # Executar o comando de build do NestJS (geralmente "tsc" ou "nest build")

      # Passo 5: Configurar SSH com a chave privada
      - name: Set up SSH key
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
        run: |          
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem  # Permissões corretas para o arquivo da chave privada
      - name: Add SSH host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 107.22.156.206 >> ~/.ssh/known_hosts
      # Passo 6: Adicionar o servidor remoto ao known_hosts
      - name: Add SSH host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 107.22.156.206 >> ~/.ssh/known_hosts

      # Passo 7: Deploy via rsync (opcional)
      - name: Deploy to server via rsync
        run: |
          rsync -avz -e "ssh -i private_key.pem" --delete \
          --exclude='node_modules/' \
          --exclude='src/' \
          --exclude='scripts/' \
          --exclude='.history/' \
          --exclude='.vscode/' \
          --exclude='laravel/' \
          --exclude='.env' \
          --exclude='*.log' \
          --exclude='_appspec.yml_' \
          --exclude='_buildspec.yml_' \
          --exclude='.prettierrc' \
          --exclude='CK*' \
          --exclude='docker-compose.yml' \
          --exclude='Dockerfile*' \
          --exclude='entrypoint.sh' \
          --exclude='.editorconfig' \
          --exclude='.env.prod' \
          --exclude='.eslintrc.js' \
          --exclude='docker.sh' \
          ./ ubuntu@107.22.156.206:/var/www/autoservice
          
      # Passo 8: Executar os comandos no servidor remoto
      - name: SSH and run commands
        run: |
          ssh -i private_key.pem ubuntu@107.22.156.206 "cd /var/www/autoservice && pnpm install && pm2 restart all"
